---
name: default

kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: unit tests composer install
  image: r.sync.pw/library/composer
  commands:
  - cd data
  - composer install --ignore-platform-reqs --quiet --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --prefer-dist --optimize-autoloader
- name: unit tests execute
  image: php:7-alpine
  commands:
  - cd data
  - vendor/bin/phpunit --colors=always --verbose --configuration phpunit.xml.dist
- name: build openapi yaml
  image: php:7-alpine
  commands:
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php composer.phar global require zircote/swagger-php
  - ~/.composer/vendor/bin/openapi /data --output /data/openapi/openapi.yml
- name: build openapi doc
  image: node:alpine
  commands:
  - npm install -g redoc-cli
  - cd data
  - redoc-cli bundle openapi/openapi.yml -o public/index.html
- name: build docker-image-tag
  when:
    event:
    - tag
  image: r.sync.pw/library/drone-plugins-docker
  settings:
    repo: r.sync.pw/project/exrate-test
    registry: r.sync.pw
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    dockerfile: Dockerfile.dist
    cache_from:
    - r.sync.pw/project/exrate-test:latest
    tags:
    - ${DRONE_TAG/\//-}
    - latest
- name: build docker-image-branch
  when:
    event:
      exclude:
        - tag
  image: r.sync.pw/library/drone-plugins-docker
  settings:
    repo: r.sync.pw/project/exrate-test
    registry: r.sync.pw
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    dockerfile: Dockerfile
    cache_from:
    - r.sync.pw/project/exrate-test:latest
    tags:
    - ${DRONE_SOURCE_BRANCH/\//-}
    - ${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:10}

image_pull_secrets:
- dockerconfigjson

