
SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

TRUNCATE `currency`;
INSERT INTO `currency` (`id`, `title`, `country`, `code`, `symbol`, `status`) VALUES
(1,	'Afghani',	'AFGHANISTAN',	'AFN',	NULL,	1),
(2,	'Euro',	'ÅLAND ISLANDS',	'EUR',	NULL,	1),
(3,	'Lek',	'ALBANIA',	'ALL',	NULL,	1),
(4,	'Algerian Dinar',	'ALGERIA',	'DZD',	NULL,	1),
(5,	'US Dollar',	'AMERICAN SAMOA',	'USD',	NULL,	1),
(6,	'Euro',	'ANDORRA',	'EUR',	NULL,	1),
(7,	'Kwanza',	'ANGOLA',	'AOA',	NULL,	1),
(8,	'East Caribbean Dollar',	'ANGUILLA',	'XCD',	NULL,	1),
(9,	'East Caribbean Dollar',	'ANTIGUA AND BARBUDA',	'XCD',	NULL,	1),
(10,	'Argentine Peso',	'ARGENTINA',	'ARS',	NULL,	1),
(11,	'Armenian Dram',	'ARMENIA',	'AMD',	NULL,	1),
(12,	'Aruban Florin',	'ARUBA',	'AWG',	NULL,	1),
(13,	'Australian Dollar',	'AUSTRALIA',	'AUD',	NULL,	1),
(14,	'Euro',	'AUSTRIA',	'EUR',	NULL,	1),
(15,	'Azerbaijan Manat',	'AZERBAIJAN',	'AZN',	NULL,	1),
(16,	'Bahamian Dollar',	'BAHAMAS (THE)',	'BSD',	NULL,	1),
(17,	'Bahraini Dinar',	'BAHRAIN',	'BHD',	NULL,	1),
(18,	'Taka',	'BANGLADESH',	'BDT',	NULL,	1),
(19,	'Barbados Dollar',	'BARBADOS',	'BBD',	NULL,	1),
(20,	'Belarusian Ruble',	'BELARUS',	'BYN',	NULL,	1),
(21,	'Euro',	'BELGIUM',	'EUR',	NULL,	1),
(22,	'Belize Dollar',	'BELIZE',	'BZD',	NULL,	1),
(23,	'CFA Franc BCEAO',	'BENIN',	'XOF',	NULL,	1),
(24,	'Bermudian Dollar',	'BERMUDA',	'BMD',	NULL,	1),
(25,	'Indian Rupee',	'BHUTAN',	'INR',	NULL,	1),
(26,	'Ngultrum',	'BHUTAN',	'BTN',	NULL,	1),
(27,	'Boliviano',	'BOLIVIA (PLURINATIONAL STATE OF)',	'BOB',	NULL,	1),
(28,	'US Dollar',	'BONAIRE, SINT EUSTATIUS AND SABA',	'USD',	NULL,	1),
(29,	'Convertible Mark',	'BOSNIA AND HERZEGOVINA',	'BAM',	NULL,	1),
(30,	'Pula',	'BOTSWANA',	'BWP',	NULL,	1),
(31,	'Norwegian Krone',	'BOUVET ISLAND',	'NOK',	NULL,	1),
(32,	'Brazilian Real',	'BRAZIL',	'BRL',	NULL,	1),
(33,	'US Dollar',	'BRITISH INDIAN OCEAN TERRITORY (THE)',	'USD',	NULL,	1),
(34,	'Brunei Dollar',	'BRUNEI DARUSSALAM',	'BND',	NULL,	1),
(35,	'Bulgarian Lev',	'BULGARIA',	'BGN',	NULL,	1),
(36,	'CFA Franc BCEAO',	'BURKINA FASO',	'XOF',	NULL,	1),
(37,	'Burundi Franc',	'BURUNDI',	'BIF',	NULL,	1),
(38,	'Cabo Verde Escudo',	'CABO VERDE',	'CVE',	NULL,	1),
(39,	'Riel',	'CAMBODIA',	'KHR',	NULL,	1),
(40,	'CFA Franc BEAC',	'CAMEROON',	'XAF',	NULL,	1),
(41,	'Canadian Dollar',	'CANADA',	'CAD',	NULL,	1),
(42,	'Cayman Islands Dollar',	'CAYMAN ISLANDS (THE)',	'KYD',	NULL,	1),
(43,	'CFA Franc BEAC',	'CENTRAL AFRICAN REPUBLIC (THE)',	'XAF',	NULL,	1),
(44,	'CFA Franc BEAC',	'CHAD',	'XAF',	NULL,	1),
(45,	'Chilean Peso',	'CHILE',	'CLP',	NULL,	1),
(46,	'Yuan Renminbi',	'CHINA',	'CNY',	NULL,	1),
(47,	'Australian Dollar',	'CHRISTMAS ISLAND',	'AUD',	NULL,	1),
(48,	'Australian Dollar',	'COCOS (KEELING) ISLANDS (THE)',	'AUD',	NULL,	1),
(49,	'Colombian Peso',	'COLOMBIA',	'COP',	NULL,	1),
(50,	'Comorian Franc',	'COMOROS (THE)',	'KMF',	NULL,	1),
(51,	'Congolese Franc',	'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',	'CDF',	NULL,	1),
(52,	'CFA Franc BEAC',	'CONGO (THE)',	'XAF',	NULL,	1),
(53,	'New Zealand Dollar',	'COOK ISLANDS (THE)',	'NZD',	NULL,	1),
(54,	'Costa Rican Colon',	'COSTA RICA',	'CRC',	NULL,	1),
(55,	'CFA Franc BCEAO',	'CÔTE D\'IVOIRE',	'XOF',	NULL,	1),
(56,	'Kuna',	'CROATIA',	'HRK',	NULL,	1),
(57,	'Cuban Peso',	'CUBA',	'CUP',	NULL,	1),
(58,	'Peso Convertible',	'CUBA',	'CUC',	NULL,	1),
(59,	'Netherlands Antillean Guilder',	'CURAÇAO',	'ANG',	NULL,	1),
(60,	'Euro',	'CYPRUS',	'EUR',	NULL,	1),
(61,	'Czech Koruna',	'CZECHIA',	'CZK',	NULL,	1),
(62,	'Danish Krone',	'DENMARK',	'DKK',	NULL,	1),
(63,	'Djibouti Franc',	'DJIBOUTI',	'DJF',	NULL,	1),
(64,	'East Caribbean Dollar',	'DOMINICA',	'XCD',	NULL,	1),
(65,	'Dominican Peso',	'DOMINICAN REPUBLIC (THE)',	'DOP',	NULL,	1),
(66,	'US Dollar',	'ECUADOR',	'USD',	NULL,	1),
(67,	'Egyptian Pound',	'EGYPT',	'EGP',	NULL,	1),
(68,	'El Salvador Colon',	'EL SALVADOR',	'SVC',	NULL,	1),
(69,	'US Dollar',	'EL SALVADOR',	'USD',	NULL,	1),
(70,	'CFA Franc BEAC',	'EQUATORIAL GUINEA',	'XAF',	NULL,	1),
(71,	'Nakfa',	'ERITREA',	'ERN',	NULL,	1),
(72,	'Euro',	'ESTONIA',	'EUR',	NULL,	1),
(73,	'Lilangeni',	'ESWATINI',	'SZL',	NULL,	1),
(74,	'Ethiopian Birr',	'ETHIOPIA',	'ETB',	NULL,	1),
(75,	'Euro',	'EUROPEAN UNION',	'EUR',	NULL,	1),
(76,	'Falkland Islands Pound',	'FALKLAND ISLANDS (THE) [MALVINAS]',	'FKP',	NULL,	1),
(77,	'Danish Krone',	'FAROE ISLANDS (THE)',	'DKK',	NULL,	1),
(78,	'Fiji Dollar',	'FIJI',	'FJD',	NULL,	1),
(79,	'Euro',	'FINLAND',	'EUR',	NULL,	1),
(80,	'Euro',	'FRANCE',	'EUR',	NULL,	1),
(81,	'Euro',	'FRENCH GUIANA',	'EUR',	NULL,	1),
(82,	'CFP Franc',	'FRENCH POLYNESIA',	'XPF',	NULL,	1),
(83,	'Euro',	'FRENCH SOUTHERN TERRITORIES (THE)',	'EUR',	NULL,	1),
(84,	'CFA Franc BEAC',	'GABON',	'XAF',	NULL,	1),
(85,	'Dalasi',	'GAMBIA (THE)',	'GMD',	NULL,	1),
(86,	'Lari',	'GEORGIA',	'GEL',	NULL,	1),
(87,	'Euro',	'GERMANY',	'EUR',	NULL,	1),
(88,	'Ghana Cedi',	'GHANA',	'GHS',	NULL,	1),
(89,	'Gibraltar Pound',	'GIBRALTAR',	'GIP',	NULL,	1),
(90,	'Euro',	'GREECE',	'EUR',	NULL,	1),
(91,	'Danish Krone',	'GREENLAND',	'DKK',	NULL,	1),
(92,	'East Caribbean Dollar',	'GRENADA',	'XCD',	NULL,	1),
(93,	'Euro',	'GUADELOUPE',	'EUR',	NULL,	1),
(94,	'US Dollar',	'GUAM',	'USD',	NULL,	1),
(95,	'Quetzal',	'GUATEMALA',	'GTQ',	NULL,	1),
(96,	'Pound Sterling',	'GUERNSEY',	'GBP',	NULL,	1),
(97,	'Guinean Franc',	'GUINEA',	'GNF',	NULL,	1),
(98,	'CFA Franc BCEAO',	'GUINEA-BISSAU',	'XOF',	NULL,	1),
(99,	'Guyana Dollar',	'GUYANA',	'GYD',	NULL,	1),
(100,	'Gourde',	'HAITI',	'HTG',	NULL,	1),
(101,	'US Dollar',	'HAITI',	'USD',	NULL,	1),
(102,	'Australian Dollar',	'HEARD ISLAND AND McDONALD ISLANDS',	'AUD',	NULL,	1),
(103,	'Euro',	'HOLY SEE (THE)',	'EUR',	NULL,	1),
(104,	'Lempira',	'HONDURAS',	'HNL',	NULL,	1),
(105,	'Hong Kong Dollar',	'HONG KONG',	'HKD',	NULL,	1),
(106,	'Forint',	'HUNGARY',	'HUF',	NULL,	1),
(107,	'Iceland Krona',	'ICELAND',	'ISK',	NULL,	1),
(108,	'Indian Rupee',	'INDIA',	'INR',	NULL,	1),
(109,	'Rupiah',	'INDONESIA',	'IDR',	NULL,	1),
(110,	'SDR (Special Drawing Right)',	'INTERNATIONAL MONETARY FUND (IMF)',	'XDR',	NULL,	1),
(111,	'Iranian Rial',	'IRAN (ISLAMIC REPUBLIC OF)',	'IRR',	NULL,	1),
(112,	'Iraqi Dinar',	'IRAQ',	'IQD',	NULL,	1),
(113,	'Euro',	'IRELAND',	'EUR',	NULL,	1),
(114,	'Pound Sterling',	'ISLE OF MAN',	'GBP',	NULL,	1),
(115,	'New Israeli Sheqel',	'ISRAEL',	'ILS',	NULL,	1),
(116,	'Euro',	'ITALY',	'EUR',	NULL,	1),
(117,	'Jamaican Dollar',	'JAMAICA',	'JMD',	NULL,	1),
(118,	'Yen',	'JAPAN',	'JPY',	NULL,	1),
(119,	'Pound Sterling',	'JERSEY',	'GBP',	NULL,	1),
(120,	'Jordanian Dinar',	'JORDAN',	'JOD',	NULL,	1),
(121,	'Tenge',	'KAZAKHSTAN',	'KZT',	NULL,	1),
(122,	'Kenyan Shilling',	'KENYA',	'KES',	NULL,	1),
(123,	'Australian Dollar',	'KIRIBATI',	'AUD',	NULL,	1),
(124,	'North Korean Won',	'KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)',	'KPW',	NULL,	1),
(125,	'Won',	'KOREA (THE REPUBLIC OF)',	'KRW',	NULL,	1),
(126,	'Kuwaiti Dinar',	'KUWAIT',	'KWD',	NULL,	1),
(127,	'Som',	'KYRGYZSTAN',	'KGS',	NULL,	1),
(128,	'Lao Kip',	'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)',	'LAK',	NULL,	1),
(129,	'Euro',	'LATVIA',	'EUR',	NULL,	1),
(130,	'Lebanese Pound',	'LEBANON',	'LBP',	NULL,	1),
(131,	'Loti',	'LESOTHO',	'LSL',	NULL,	1),
(132,	'Rand',	'LESOTHO',	'ZAR',	NULL,	1),
(133,	'Liberian Dollar',	'LIBERIA',	'LRD',	NULL,	1),
(134,	'Libyan Dinar',	'LIBYA',	'LYD',	NULL,	1),
(135,	'Swiss Franc',	'LIECHTENSTEIN',	'CHF',	NULL,	1),
(136,	'Euro',	'LITHUANIA',	'EUR',	NULL,	1),
(137,	'Euro',	'LUXEMBOURG',	'EUR',	NULL,	1),
(138,	'Pataca',	'MACAO',	'MOP',	NULL,	1),
(139,	'Denar',	'NORTH MACEDONIA',	'MKD',	NULL,	1),
(140,	'Malagasy Ariary',	'MADAGASCAR',	'MGA',	NULL,	1),
(141,	'Malawi Kwacha',	'MALAWI',	'MWK',	NULL,	1),
(142,	'Malaysian Ringgit',	'MALAYSIA',	'MYR',	NULL,	1),
(143,	'Rufiyaa',	'MALDIVES',	'MVR',	NULL,	1),
(144,	'CFA Franc BCEAO',	'MALI',	'XOF',	NULL,	1),
(145,	'Euro',	'MALTA',	'EUR',	NULL,	1),
(146,	'US Dollar',	'MARSHALL ISLANDS (THE)',	'USD',	NULL,	1),
(147,	'Euro',	'MARTINIQUE',	'EUR',	NULL,	1),
(148,	'Ouguiya',	'MAURITANIA',	'MRU',	NULL,	1),
(149,	'Mauritius Rupee',	'MAURITIUS',	'MUR',	NULL,	1),
(150,	'Euro',	'MAYOTTE',	'EUR',	NULL,	1),
(151,	'ADB Unit of Account',	'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',	'XUA',	NULL,	1),
(152,	'Mexican Peso',	'MEXICO',	'MXN',	NULL,	1),
(153,	'US Dollar',	'MICRONESIA (FEDERATED STATES OF)',	'USD',	NULL,	1),
(154,	'Moldovan Leu',	'MOLDOVA (THE REPUBLIC OF)',	'MDL',	NULL,	1),
(155,	'Euro',	'MONACO',	'EUR',	NULL,	1),
(156,	'Tugrik',	'MONGOLIA',	'MNT',	NULL,	1),
(157,	'Euro',	'MONTENEGRO',	'EUR',	NULL,	1),
(158,	'East Caribbean Dollar',	'MONTSERRAT',	'XCD',	NULL,	1),
(159,	'Moroccan Dirham',	'MOROCCO',	'MAD',	NULL,	1),
(160,	'Mozambique Metical',	'MOZAMBIQUE',	'MZN',	NULL,	1),
(161,	'Kyat',	'MYANMAR',	'MMK',	NULL,	1),
(162,	'Namibia Dollar',	'NAMIBIA',	'NAD',	NULL,	1),
(163,	'Rand',	'NAMIBIA',	'ZAR',	NULL,	1),
(164,	'Australian Dollar',	'NAURU',	'AUD',	NULL,	1),
(165,	'Nepalese Rupee',	'NEPAL',	'NPR',	NULL,	1),
(166,	'Euro',	'NETHERLANDS (THE)',	'EUR',	NULL,	1),
(167,	'CFP Franc',	'NEW CALEDONIA',	'XPF',	NULL,	1),
(168,	'New Zealand Dollar',	'NEW ZEALAND',	'NZD',	NULL,	1),
(169,	'Cordoba Oro',	'NICARAGUA',	'NIO',	NULL,	1),
(170,	'CFA Franc BCEAO',	'NIGER (THE)',	'XOF',	NULL,	1),
(171,	'Naira',	'NIGERIA',	'NGN',	NULL,	1),
(172,	'New Zealand Dollar',	'NIUE',	'NZD',	NULL,	1),
(173,	'Australian Dollar',	'NORFOLK ISLAND',	'AUD',	NULL,	1),
(174,	'US Dollar',	'NORTHERN MARIANA ISLANDS (THE)',	'USD',	NULL,	1),
(175,	'Norwegian Krone',	'NORWAY',	'NOK',	NULL,	1),
(176,	'Rial Omani',	'OMAN',	'OMR',	NULL,	1),
(177,	'Pakistan Rupee',	'PAKISTAN',	'PKR',	NULL,	1),
(178,	'US Dollar',	'PALAU',	'USD',	NULL,	1),
(179,	'Balboa',	'PANAMA',	'PAB',	NULL,	1),
(180,	'US Dollar',	'PANAMA',	'USD',	NULL,	1),
(181,	'Kina',	'PAPUA NEW GUINEA',	'PGK',	NULL,	1),
(182,	'Guarani',	'PARAGUAY',	'PYG',	NULL,	1),
(183,	'Sol',	'PERU',	'PEN',	NULL,	1),
(184,	'Philippine Peso',	'PHILIPPINES (THE)',	'PHP',	NULL,	1),
(185,	'New Zealand Dollar',	'PITCAIRN',	'NZD',	NULL,	1),
(186,	'Zloty',	'POLAND',	'PLN',	NULL,	1),
(187,	'Euro',	'PORTUGAL',	'EUR',	NULL,	1),
(188,	'US Dollar',	'PUERTO RICO',	'USD',	NULL,	1),
(189,	'Qatari Rial',	'QATAR',	'QAR',	NULL,	1),
(190,	'Euro',	'RÉUNION',	'EUR',	NULL,	1),
(191,	'Romanian Leu',	'ROMANIA',	'RON',	NULL,	1),
(192,	'Russian Ruble',	'RUSSIAN FEDERATION (THE)',	'RUB',	NULL,	1),
(193,	'Rwanda Franc',	'RWANDA',	'RWF',	NULL,	1),
(194,	'Euro',	'SAINT BARTHÉLEMY',	'EUR',	NULL,	1),
(195,	'Saint Helena Pound',	'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',	'SHP',	NULL,	1),
(196,	'East Caribbean Dollar',	'SAINT KITTS AND NEVIS',	'XCD',	NULL,	1),
(197,	'East Caribbean Dollar',	'SAINT LUCIA',	'XCD',	NULL,	1),
(198,	'Euro',	'SAINT MARTIN (FRENCH PART)',	'EUR',	NULL,	1),
(199,	'Euro',	'SAINT PIERRE AND MIQUELON',	'EUR',	NULL,	1),
(200,	'East Caribbean Dollar',	'SAINT VINCENT AND THE GRENADINES',	'XCD',	NULL,	1),
(201,	'Tala',	'SAMOA',	'WST',	NULL,	1),
(202,	'Euro',	'SAN MARINO',	'EUR',	NULL,	1),
(203,	'Dobra',	'SAO TOME AND PRINCIPE',	'STN',	NULL,	1),
(204,	'Saudi Riyal',	'SAUDI ARABIA',	'SAR',	NULL,	1),
(205,	'CFA Franc BCEAO',	'SENEGAL',	'XOF',	NULL,	1),
(206,	'Serbian Dinar',	'SERBIA',	'RSD',	NULL,	1),
(207,	'Seychelles Rupee',	'SEYCHELLES',	'SCR',	NULL,	1),
(208,	'Leone',	'SIERRA LEONE',	'SLL',	NULL,	1),
(209,	'Singapore Dollar',	'SINGAPORE',	'SGD',	NULL,	1),
(210,	'Netherlands Antillean Guilder',	'SINT MAARTEN (DUTCH PART)',	'ANG',	NULL,	1),
(211,	'Sucre',	'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS \"SUCRE\"',	'XSU',	NULL,	1),
(212,	'Euro',	'SLOVAKIA',	'EUR',	NULL,	1),
(213,	'Euro',	'SLOVENIA',	'EUR',	NULL,	1),
(214,	'Solomon Islands Dollar',	'SOLOMON ISLANDS',	'SBD',	NULL,	1),
(215,	'Somali Shilling',	'SOMALIA',	'SOS',	NULL,	1),
(216,	'Rand',	'SOUTH AFRICA',	'ZAR',	NULL,	1),
(217,	'South Sudanese Pound',	'SOUTH SUDAN',	'SSP',	NULL,	1),
(218,	'Euro',	'SPAIN',	'EUR',	NULL,	1),
(219,	'Sri Lanka Rupee',	'SRI LANKA',	'LKR',	NULL,	1),
(220,	'Sudanese Pound',	'SUDAN (THE)',	'SDG',	NULL,	1),
(221,	'Surinam Dollar',	'SURINAME',	'SRD',	NULL,	1),
(222,	'Norwegian Krone',	'SVALBARD AND JAN MAYEN',	'NOK',	NULL,	1),
(223,	'Swedish Krona',	'SWEDEN',	'SEK',	NULL,	1),
(224,	'Swiss Franc',	'SWITZERLAND',	'CHF',	NULL,	1),
(225,	'Syrian Pound',	'SYRIAN ARAB REPUBLIC',	'SYP',	NULL,	1),
(226,	'New Taiwan Dollar',	'TAIWAN (PROVINCE OF CHINA)',	'TWD',	NULL,	1),
(227,	'Somoni',	'TAJIKISTAN',	'TJS',	NULL,	1),
(228,	'Tanzanian Shilling',	'TANZANIA, UNITED REPUBLIC OF',	'TZS',	NULL,	1),
(229,	'Baht',	'THAILAND',	'THB',	NULL,	1),
(230,	'US Dollar',	'TIMOR-LESTE',	'USD',	NULL,	1),
(231,	'CFA Franc BCEAO',	'TOGO',	'XOF',	NULL,	1),
(232,	'New Zealand Dollar',	'TOKELAU',	'NZD',	NULL,	1),
(233,	'Pa’anga',	'TONGA',	'TOP',	NULL,	1),
(234,	'Trinidad and Tobago Dollar',	'TRINIDAD AND TOBAGO',	'TTD',	NULL,	1),
(235,	'Tunisian Dinar',	'TUNISIA',	'TND',	NULL,	1),
(236,	'Turkish Lira',	'TURKEY',	'TRY',	NULL,	1),
(237,	'Turkmenistan New Manat',	'TURKMENISTAN',	'TMT',	NULL,	1),
(238,	'US Dollar',	'TURKS AND CAICOS ISLANDS (THE)',	'USD',	NULL,	1),
(239,	'Australian Dollar',	'TUVALU',	'AUD',	NULL,	1),
(240,	'Uganda Shilling',	'UGANDA',	'UGX',	NULL,	1),
(241,	'Hryvnia',	'UKRAINE',	'UAH',	NULL,	1),
(242,	'UAE Dirham',	'UNITED ARAB EMIRATES (THE)',	'AED',	NULL,	1),
(243,	'Pound Sterling',	'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',	'GBP',	NULL,	1),
(244,	'US Dollar',	'UNITED STATES MINOR OUTLYING ISLANDS (THE)',	'USD',	NULL,	1),
(245,	'US Dollar',	'UNITED STATES OF AMERICA (THE)',	'USD',	NULL,	1),
(246,	'Peso Uruguayo',	'URUGUAY',	'UYU',	NULL,	1),
(247,	'Unidad Previsional',	'URUGUAY',	'UYW',	NULL,	1),
(248,	'Uzbekistan Sum',	'UZBEKISTAN',	'UZS',	NULL,	1),
(249,	'Vatu',	'VANUATU',	'VUV',	NULL,	1),
(250,	'Bolívar Soberano',	'VENEZUELA (BOLIVARIAN REPUBLIC OF)',	'VES',	NULL,	1),
(251,	'Dong',	'VIET NAM',	'VND',	NULL,	1),
(252,	'US Dollar',	'VIRGIN ISLANDS (BRITISH)',	'USD',	NULL,	1),
(253,	'US Dollar',	'VIRGIN ISLANDS (U.S.)',	'USD',	NULL,	1),
(254,	'CFP Franc',	'WALLIS AND FUTUNA',	'XPF',	NULL,	1),
(255,	'Moroccan Dirham',	'WESTERN SAHARA',	'MAD',	NULL,	1),
(256,	'Yemeni Rial',	'YEMEN',	'YER',	NULL,	1),
(257,	'Zambian Kwacha',	'ZAMBIA',	'ZMW',	NULL,	1),
(258,	'Zimbabwe Dollar',	'ZIMBABWE',	'ZWL',	NULL,	1),
(259,	'Bond Markets Unit European Composite Unit (EURCO)',	'ZZ01_Bond Markets Unit European_EURCO',	'XBA',	NULL,	1),
(260,	'Bond Markets Unit European Monetary Unit (E.M.U.-6)',	'ZZ02_Bond Markets Unit European_EMU-6',	'XBB',	NULL,	1),
(261,	'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',	'ZZ03_Bond Markets Unit European_EUA-9',	'XBC',	NULL,	1),
(262,	'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',	'ZZ04_Bond Markets Unit European_EUA-17',	'XBD',	NULL,	1),
(263,	'Codes specifically reserved for testing purposes',	'ZZ06_Testing_Code',	'XTS',	NULL,	1),
(264,	'The codes assigned for transactions where no currency is involved',	'ZZ07_No_Currency',	'XXX',	NULL,	1),
(265,	'Gold',	'ZZ08_Gold',	'XAU',	NULL,	1),
(266,	'Palladium',	'ZZ09_Palladium',	'XPD',	NULL,	1),
(267,	'Platinum',	'ZZ10_Platinum',	'XPT',	NULL,	1),
(268,	'Silver',	'ZZ11_Silver',	'XAG',	NULL,	1);
